### ISSUE TITLE
Ideenskizze

### ISSUE THREAD

**Issue by deeptensornn** [deeptensornn/DeepSimpleL#1]
Fachsprache -> Einfache-Sprache
Eine Übersetzung die mehr und mehr notwendig wird. Auf Grund: 
- unterschiedlichen Bildungsniveaus
- ethnischer Herkunft
- Globalisierung

**Comment by kindustrii** [comment]
Wird eine komplexe/komplizierte/schwere Sprache bzw. Fachsprache in Texten verwendet, dann sind die Inhalte dieser Texte nur denjenigen vorbehalten, die bestimmte Begriffe und Bedeutungen von Fremdwörtern kennen. Fachsprache wird somit zur Hürde, sich neues Wissen anzueignen. 

Eine leichte Sprache gewährt einen barrierefreien Zugang zu Wissen und ermöglicht es jedem, unabhängig von seinen sprachlichen Kompetenzen, sich mit neuen Themen zu befassen und sich neues Wissen anzueignen.

**Comment by deeptensornn** [comment]
In Formularentwurf "Einreichung ..."
2.3 Welchen Nutzen hat die skizzierte Idee für das Gemeinwohl?
übernommen. Wäre eventuell auch unter anderem Punkt interessant.
