### ISSUE TITLE
[DeepSimpleL/Einreichungsformular_Ideenwettbewerb] 2.7 Auf welcher Datenbasis könnte die Idee realisiert werden?

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#10]
Als weiter Quelle für Daten, in unserem Fall handelt es sich um Texte, besteht die Möglichkeit auf Bücher zurückzugreifen, bei denen bereits das Urheberrecht abgelaufen ist, oder die über kein Urheberrecht verfügen.

*Siehe Issue #9*
Zusätzlich gibt es vortrainierte Word Embeddings, auf die wir zugreifen könnten.
Hier einige Quellen dazu:
[http://www.spinningbytes.com/resources/wordembeddings/](url)
[https://deepset.ai/german-word-embeddings](url)
[https://devmount.github.io/GermanWordEmbeddings/](url)

**Comment by deeptensornn** [comment]
Werde ich offen lassen - ist für die Konzepterstellung meiner Ansicht nach von Bedeutung.

**Comment by deeptensornn** [comment]
bleibt offen, oder bei ausreichend Zeit eine Datei Konzept in die das rein kommt.

**Comment by kindustrii** [comment]
Sollen wir die Konzept-Knospe aus der main-branch in die DeepSimpleL branch verschieben? Und dann für den LibreTranslator eine eigene erstellen?

**Comment by deeptensornn** [comment]
Ich denke eher daran nach der Anmeldung zwei Projekte aufzumachen, damit wir richtig mergen können. Bei meinen Sachen hab ich immer ein Verzeichnis Mülleimer oder Ideen. Dafür ist die Knopse eigentlich Ersatz. Da können wir noch was reinwerfen bis die Anmeldung durch ist. Das muss ich Alles noch dem Hotz vorlegen. Mal sehen was für Ansprüche er stellt. Die PDFs gefallen mir vom Layout nicht. Baue die gerade um. Da muss man sich ja schämen für.
