### ISSUE TITLE
[DeepSimpleL/Einreichungsformular_Ideenwettbewerb] 2.3 Welchen Nutzen hat die skizzierte Idee für das Gemeinwohl?

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#11]
DeepSimpleL könnte ebenfalls dazu verwendet werden um behördliche Anträge und Formulare zu übersetzen. Da diese oft in einem schwer verständlichen Beamtendeutsch verfasst sind, haben viele Menschen Schwierigkeiten diese Formulare richtig auszufüllen.

AGBs und insbesondere Datenschutzerklärungen von digitalen Produkten und Dienstleistungen sind ebenfalls oft in einer Sprache formuliert, die es den Nutzern erschwert zu verstehen, wie ihre personenbezogenen Daten verarbeitet werden. Viele  machen sich nicht mehr die Mühe diese komplizierten Texte zu lesen. Mit DeepSimpeL wäre es möglich auch diese Texte in eine Leichter-Sprache zu übersetzen.

**Comment by deeptensornn** [comment]
Den Text oder Teile werde ich versuchen noch irgendwo rein zu quetschen.

**Comment by deeptensornn** [comment]
Soweit geändert
