### ISSUE TITLE
Änderung Kooperationsvertrag

### ISSUE THREAD

**Issue by deeptensornn** [deeptensornn/DeepSimpleL#13]
Weil wir wohl den Verlag mit ins Boot bekommen, habe ich eine Änderung bezüglich der Verteilung des Geldes aufgenommen. Treuhändlerich will ich das nicht mehr machen. Ich bin nun für eine Verteilung direkt nach Erhalt zu gleichen Teilen. Hoffe das Herr Hotz uns 'freiwillig' entgegenkommt (wie ich ihn kenne). Hoffe du bist erst mal einverstanden? Ist alles noch vorläufig. Ich will bis Montag 12 Uhr die Dokumente in einer vorläufigen Form an dich und den Verlag senden, damit man beim Jedermann sieht, wie das etwa aussieht. Um die Zeit müsste Frank im Büro sein. Jedenfalls war es damals so.

**Comment by kindustrii** [comment]
Ja das passt so für mich.
Wobei der Verlag vermutlich auch irgendwelche Themen in die Vereinbarung aufnehmen wollen wird. Aber ich bin da offen und unkompliziert.

**Comment by deeptensornn** [comment]
erledigt
