### ISSUE TITLE
[LibreTranslator/Einreichungsformular_Ideenwettbewerb] 2.2 Kurzbeschreibung

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#14]
> LibreTranslator ist eine Dolmetscher-Anwendung zur Übersetzung von Text aus einer beliebigen Sprache in eine andere beliebige Sprache. Sie soll beim Arbeiten am PC jederzeit zur Verfügung stehen und auf Wunsch problemlos Übersetzungen anbieten

Wir sollten die Kurzbeschreibung vielleicht um etwas ergänzen, das das Interesse weckt. Weil so liest man die Beschreibung jetzt so wie sie ist, dann kommt einem das ganze als nicht sehr neu vor. 280 Zeichen sind sehr knapp dafür. Sollen wir zumindest den Punkt, dass es sich um eine Open-Source Anwendung handelt aufnehmen?

**Comment by deeptensornn** [comment]
In jdem Fall. Ich denke Open Source beim Translator ist der Hauptpunkt.
