### ISSUE TITLE
[LibreTranslator/Einreichungsformular_Ideenwettbewerb] 2.4 Welche technologische Umsetzung wird angestrebt?

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#15]
Denkbar wäre es auch das ganze nicht als reinen Textübersetzter anzubieten, sondern auch für Video- und Audio-Dateien. Als technische Umsetzung könnten wir die Tonspur nach gesprochenem durchsuchen, in Text umwandeln, den Text mit dem LibreTranslator-NN übersetzten, den unübersetzten Text wieder in eine Audio-Datei umwandeln und die ursprüngliche damit Tonspur überlagern. 

Und/Oder, das ganze als Plugin entwickeln. Z.B. ein Plugin für Browser. Dann könnte LibreTranslator für alles mögliche verwendet werden. Das Plugin könnte auch auch Bilddateien nach Texten durchsuchen und diese übersetzten. Natürlich auch für normale Texte, Videos, und allem anderen was sich in einem Browser darstellen und übersetzten lässt.

**Comment by deeptensornn** [comment]
Ja, das ist anzudenken. Ich setze das mal in die Knospe rein.
