### ISSUE TITLE
[LibreTranslator/Einreichungsformular_Ideenwettbewerb] 2.3 Welchen Nutzen hat die skizzierte Idee für das Gemeinwohl?

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#17]
DeepL und Google haben ein eine Schwäche. Und zwar kann weiß man als Nutzer eigentlich nicht, ob ich dem glauben kann was da übersetzt wurde und was nicht. Wenn ich etwas in arabische übersetzte, selber aber gar kein arabisch kann, woher weiß ich dann, dass die Übersetzung gut bzw. überhaupt richtig ist? Besonders bei wichtigen Dokumenten und Texten ist ist es eine problematische Situation. 

> هل تمت ترجمة هذا النص بشكل صحيح؟

Ich muss mich darauf verlassen, oder jemanden suchen, der arabisch spricht und bestätigen lassen.

Idee: LibreTranslator durchläuft eine Art TÜV, in dem von behördlicher Stelle eine Freigabe erfolgt.
Damit wäre das Vertrauen der Nutzer deutlich höher.

**Comment by deeptensornn** [comment]
Wenn das machbar wäre wäre das natürlich toll. Da kann der Frank uns vielleicht unterstützen. Das muss in jedem Fall in die Knospe. Bei Chinesisch ist das beisielsweise recht problematisch. Aber das zu realisieren wrde bedeuten das Prgramm müsse regelmässig von einer öffentlichen Stelle geprüft werden. Dafür könnte man eventuell sogar den TÜV gewinnen.
