### ISSUE TITLE
Einreichung zum Ideenwettbewerb

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#2]
Folgende Formulare sollen bis zum 15.11.20 ausgefüllt und unterschrieben an cip-wettbewerb@bmas.bund.de eingereicht werden.

- [ ] Formular „Einreichung zum Ideenwettbewerb“
- [ ] Rechtsverbindliche Erklärung
- [ ] Kooperationsvereinbarung

[Muster_Kooperationsvereinbarung.pdf](https://github.com/deeptensornn/DeepSimpleL/files/5483810/Muster_Kooperationsvereinbarung.pdf)
[Rechtsverbindliche_Erklaerung.pdf](https://github.com/deeptensornn/DeepSimpleL/files/5483811/Rechtsverbindliche_Erklaerung.pdf)
[Formular_Einreichung_zum_Ideenwettbewerb.pdf](https://github.com/deeptensornn/DeepSimpleL/files/5483812/Formular_Einreichung_zum_Ideenwettbewerb.pdf)

**Comment by deeptensornn** [comment]
Ok - in README übernommen
