### ISSUE TITLE
[DeepSimpleL/Kooperationsvereinbarung] 3. Projektidee

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#4]
`[...] Der Nutzer kann verschiedene Stufen der Verständlichkeit wählen.`

Macht es Sinn mehrere Stufen der Verständlichkeit zu implementieren? 
Ich kann keine (nichtdiskriminierenden) Kriterien finden, nach denen die Stufen sinnvoll voneinander abgegrenzt werden können. 

Mir fällt aktuell kein Szenario ein, bei dem das von großem Nutzen wäre. Vielleicht sollten wir diesen Punkt an einer anderen Stelle im Text erwähnen, damit nicht eine allzu hohe Priorität mit dieser Funktion assoziiert wird.

Es sei denn, ich unterschätze die Vorteile/Mehrwert von mehreren Stufen der Verständlichkeit.

**Comment by deeptensornn** [comment]
<i>"Handle so, dass die Maxime deines Willens jederzeit zugleich als Prinzip einer allgemeinen Gesetzgebung gelten könne."</i> - § 7 Grundgesetz der reinen praktischen Vernunft in der Kritik der praktischen Vernunft, S. 36

1. Stufe:
"Richte die Gesichtspunkte deines Handelns nach einem allgemein als vernünftig anerkannten Grundsatz aus."  

2. Stufe:
"Richte dein Handeln so aus, als müsse es als Grundlage einer allgemeinen Gesetzgebung herhalten." 

3. Stufe:
"Mache alles so, wie alle Anderen es an deiner Stelle auch machen würden."

4. Stufe:
"Liebe deinen Nächsten wie dich selbst" Jesus, Galater 5.14. 2.

Deinen Einwand verstehe ich schon. Aber wo ist die Basis allgemeinen Verständnisses? Eine Realisierung mehrerer Stufen könnte das Projekt natürlich unnötig aufblähen. Je nach Anwendung, ich kenne das von einer Rehaklinik die die Arbeiterwohlfahrt betreibt, gibt es noch weit krassere  Verständnisstufen bei den Kindern, Jugendlichen und Erwachsenen.  
Daher würde ich den Punkt hier trotzdem gerne drin lassen. Realisieren sollte man vielleicht erst einmal eine Ebene. Werde das auch so übernehmen.

**Comment by kindustrii** [comment]
Sorry, ausversehen geschlossen

**Comment by deeptensornn** [comment]
Natürlich, können wir glaube ich dichtmachen.
