### ISSUE TITLE
[DeepSimpleL/Kooperationsvereinbarung] 5. Zusammenarbeit

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#6]
Die Auszahlung der Prämie erfolgt in drei Teilen. Für jeden Teile müssen bestimmten Voraussetzungen erfüllt werden.
Z.B. muss für den ersten Teil zwingend an einem Workshop teilgenommen werden.

Wir sollten regeln wer an solchen Veranstaltungen teilnimmt.
Es wird auch andere Veranstaltungen geben (z.B. die Vorstellung der Idee) die voraussichtlich virtuell durchgeführt werden. Auch für den Fall einer Präsenzveranstaltung sollten wir die Teilnehme sicherstellen.

**Comment by deeptensornn** [comment]
Bin leider 'Corona-Hotspot' ;-), schon auf Grund meines Alters. Deshalb wäre jetzt was festzulegen ziemlich in den Wind geschossen. Wir wissen ja auch nicht wie das weitergeht, mit der Seuche. Natürlich wäre schön wenn jeweils wenigsten einer teilnehmen könnte. Das müssten wir eigentlich hinbekommen. Vielleicht kommt ja da auch noch Hilfe vom 'institutionellen' Teilnehmer den wir noch nicht kennen. Über zu wenig freie Zeit kann ich  nicht klagen.

**Comment by deeptensornn** [comment]
Vor erst lasse ich das mal offen. Reinschreiben wollte ich aber nichts, wir strafen uns ja selbst, wenn wir nicht mitmachen.

**Comment by deeptensornn** [comment]
habe Infos vom BMAS:

Liebe Frau bzw. lieber Herr Wolmeringer,

vielen Dank für Ihr Interesse an unserem Ideenwettbewerb „Gemeinsam wird es KI“. Der Pitch ist derzeit in Planung, aber es wird sich definitiv um ein virtuelles Format handeln, das es ermöglichen wird, die Ideen auch ohne ortsanwesend zu sein, angemessen zu präsentieren.

Wir sind gespannt auf Ihre Idee!

Das Team der Civic Innovation Platform

**Comment by kindustrii** [comment]
Ok, super. Dann sollten wir die Teilnahme wohl sicherstellen können bei den Veranstaltungen.
Ich glaube der Punkt kann zugemacht werden, oder?

**Comment by deeptensornn** [comment]
Vielleicht unterstützt man uns ja auch vom Verlag her. Mal sehen. Wie eng die Zusammenarbeit wird.
