### ISSUE TITLE
[DeepSimpleL/Kooperationsvereinbarung] 6. Rechte Dritter 

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#7]
Wir werden für die Entwicklung der NNs bestimmte Python Libraries verwenden, die unter unterschiedlichen Lizenzen zur Verfügung stehen. Wir müssen darauf achten, dass wir hier keine Rechte verletzen, insbesondere wenn wir Teile des Codes nicht öffentlich zugänglich machen werden.

**Comment by deeptensornn** [comment]
Das ist natürlich war. Das Problem haben wir aber ständig. 
Nur heißt es ja im Prospekt:
'Die Preisträgerinnen und Preisträger erlangen
dadurch die Möglichkeit, ihre Ideenskizze zu einem förderfähigen Konzept auszuarbeiten,
das entweder im Rahmen eines Förderprogramms des BMAS eingereicht werden kann
oder sich für andere Förderprogramme des Bundes qualifiziert.'

Wenn ich das richtig verstehe, sind wir da vom Coding noch weit weg.
Es geht wohl mehr um die Rechte an den Medien, die wir für das Konzept nutzen.
