### ISSUE TITLE
[DeepSimpleL/Einreichungsformular_Ideenwettbewerb] 2.2 Kurzbeschreibung

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#8]
Wir sollten die Kurzbeschreibungen der Idee in den beiden folgenden Formularen angleichen:

1. Einreichungsformular_Ideenwettbewerb (Abschnitt 2.2)
2. Kooperationsvereinbarung (Abschnitt 3.)

**Comment by deeptensornn** [comment]
Ist sinnvoll. Werde mich nachher noch dranmachen.

**Comment by deeptensornn** [comment]
erledigt
