### ISSUE TITLE
[DeepSimpleL/Einreichungsformular_Ideenwettbewerb] 2.4 Welche technologische Umsetzung wird angestrebt?

### ISSUE THREAD

**Issue by kindustrii** [deeptensornn/DeepSimpleL#9]
`[...] Da neuronale Netze nur nummerische Daten verarbeiten können muss eine Umsetzung von Strings oder kontextbezogenen längeren Texten in Ziffernfolgen durchgeführt werden. Denkbar wäre eine Art Thesaurus der Fachsprache Leichter-Sprache gegenüberstellt und intern Ziffernkodes nutzt, die ein NN kontextspezifisch zu leicht verständlichen Texten umsetzt. [...]`.

Ich bin der Meinung, dass im Kontext von Deep Learning die technologische Umsetzung auf folgende Art sinnvoller wäre:

`Da neuronale Netze nur nummerische Daten verarbeiten können muss eine Umsetzung von Strings oder kontextbezogenen längeren Texten in Ziffernfolgen durchgeführt werden.`

> Damit Texte von neuronalen Netzen verarbeitet werden, nutzen wir das sog. Word Embedding. Mit dieser Methode werden einzelne Wörter, aber auch ganze Sätze als multi-dimensionale Vektoren repräsentiert. Weiterhin ermöglicht diese Methode unterschiedliche Sätze hinsichtlich des Kontexts miteinander zu vergleichen.

`Denkbar wäre eine Art Thesaurus der Fachsprache Leichter-Sprache gegenüberstellt und intern Ziffernkodes nutzt, die ein NN kontextspezifisch zu leicht verständlichen Texten umsetzt.`

> Die Transformation von Fachsprache in Leichter-Sprache soll von einem entsprechend trainierten Neuronalen Netz durchgeführt werden. Als Trainingsdaten für dieses NN werden Zwei Texte benötigt, die exakt dieselbe Information enthalten, aber einmal in Fachsprache und einmal in Leichter-Sprache verfasst sind. Diese Trainingsdaten stehen uns nicht in ausreichendem Maße zur Verfügung. 
Aus diesem Grund soll das NN während dem Training als GAN (Generative Adversarial Network) realisiert werden. Dabei werden wir Modifizierungen an den üblichen GAN-Algorithmen vornehmen müssen, um den beiden Voraussetzung a) Vermeidung von Informationsverlust durch Transformation und b) Sicherstellung, dass tatsächlich in die Leichter-Sprache transformiert wurde.

**Comment by deeptensornn** [comment]
GANs kenne ich von der Erzeugung fotorealistischer Bilder her. An so etwas dachte ich auch. Sozusagen ein Netz das Leichte Sprache erzeugt (Generator) und ein Netz (Diskriminator) das aus Leichter-Sprache wieder Kauderwelsch baut ;-). Das wird ein Spaß.
Hier denke ich sollten wir uns noch nicht ganz so festlegen. Das müssen wir in der Konzepterstellung klären.
Der Text ist ohnhin zu lang ich kürze ihn mal und deute was an.
